# Build stage
FROM node:21-alpine AS build

WORKDIR /app

# Install dependencies
RUN npm install -g npm@10.2.3

RUN apk update && apk upgrade

COPY ./cms/package*.json /app/

RUN npm install && npm cache clean --force

COPY ./cms .

ENV PATH ./cms/node_modules/.bin/:$PATH