# Build stage
FROM node:21-alpine AS build

# Set Workdir to /app
WORKDIR /app

# Install dependencies
RUN npm install -g npm@10.2.3

# Copy package and lock files
COPY ./cms .

RUN npm install
RUN npm run build

# Production stage
FROM node:21-alpine AS production

WORKDIR /app
COPY --from=build /app/.output .

EXPOSE 3000

# Start the app
CMD [ "node", "./server/index.mjs" ]
