name: API Setup & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Install Composer Dependencies
        run: docker-compose exec -T php composer install

      - name: Copy .env
        run: docker-compose exec -T php cp .env.example .env

      - name: Generate Application Key
        run: docker-compose exec -T php php artisan key:generate

      - name: Storage Link
        run: docker-compose exec -T php php artisan storage:link

      - name: Lint
        run: docker compose exec php ./vendor/bin/pint --test

      - name: Run Tests
        run: docker compose exec -T php vendor/bin/phpunit --coverage-text --testsuite Feature
