name: Laravel Docker Test

on:
  push:
    branches:
      - main

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for Services
        run: docker-compose exec php sh -c "while ! nc -z mysql 3306; do sleep 1; done"

      - name: Install Composer Dependencies
        run: docker-compose exec php composer install

      - name: Copy .env
        run: docker-compose exec php cp .env.example .env

      - name: Generate Application Key
        run: docker-compose exec php php artisan key:generate

      - name: Run Migrations and Seed the Database
        run: docker-compose exec php php artisan migrate --seed

      - name: Run Tests
        run: docker-compose exec php php artisan test
